version: '3.7'

services:
  psql:
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=category 
    volumes:
      - psql_volume:/bitnami/postgresql

volumes:
  psql_volume: